"""empty message

Revision ID: 17ea64ee8d1e
Revises: 7a7b8c3fd19
Create Date: 2013-12-22 14:14:40.894396

"""

# revision identifiers, used by Alembic.
revision = '17ea64ee8d1e'
down_revision = '7a7b8c3fd19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
