"""empty message

Revision ID: 1c3293214ec1
Revises: 1f10ba784ed8
Create Date: 2014-01-02 08:19:44.831592

"""

# revision identifiers, used by Alembic.
revision = '1c3293214ec1'
down_revision = '1f10ba784ed8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'received_transitory_glance', ['receiver_twitter_id', 'sender_twitter_id'])
    op.add_column('twitter_friends_cache', sa.Column('twitter_name', sa.String(length=255), nullable=True))
    op.drop_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache')
    op.create_unique_constraint(None, 'twitter_friends_cache', ['twitter_id', 'friend_twitter_id'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'twitter_friends_cache')
    op.create_unique_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache', [u'friend_twitter_id', u'twitter_id'])
    op.drop_column('twitter_friends_cache', 'twitter_name')
    op.drop_constraint(None, 'received_transitory_glance')
    ### end Alembic commands ###
