"""empty message

Revision ID: 1c672cc5edf2
Revises: 387b1e58aad5
Create Date: 2013-12-16 10:38:27.773987

"""

# revision identifiers, used by Alembic.
revision = '1c672cc5edf2'
down_revision = '387b1e58aad5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connections', sa.Column('full_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connections', 'full_name')
    ### end Alembic commands ###
