"""empty message

Revision ID: 1cb8a1c5d448
Revises: 1c672cc5edf2
Create Date: 2013-12-16 15:11:58.552861

"""

# revision identifiers, used by Alembic.
revision = '1cb8a1c5d448'
down_revision = '1c672cc5edf2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glances',
    sa.Column('sending_user_id', sa.Integer(), nullable=False),
    sa.Column('receiving_user_id', sa.Integer(), nullable=False),
    sa.Column('last_glance_made_at', sa.DateTime(), nullable=True),
    sa.Column('last_glance_noticed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sending_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sending_user_id', 'receiving_user_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glances')
    ### end Alembic commands ###
