"""empty message

Revision ID: 1f10ba784ed8
Revises: 52bf871e32f1
Create Date: 2013-12-31 14:48:16.687451

"""

# revision identifiers, used by Alembic.
revision = '1f10ba784ed8'
down_revision = '52bf871e32f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('received_transitory_glance',
    sa.Column('receiver_twitter_id', sa.String(length=255), nullable=False),
    sa.Column('sender_twitter_id', sa.String(length=255), nullable=False),
    sa.Column('most_recent', sa.DateTime(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('receiver_twitter_id', 'sender_twitter_id'),
    sa.UniqueConstraint('receiver_twitter_id','sender_twitter_id')
    )
    op.drop_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache')
    op.create_unique_constraint(None, 'twitter_friends_cache', ['twitter_id', 'friend_twitter_id'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'twitter_friends_cache')
    op.create_unique_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache', [u'friend_twitter_id', u'twitter_id'])
    op.drop_table('received_transitory_glance')
    ### end Alembic commands ###
