"""empty message

Revision ID: 26838fd9f692
Revises: b15ec99bb13
Create Date: 2013-12-22 23:13:40.366573

"""

# revision identifiers, used by Alembic.
revision = '26838fd9f692'
down_revision = 'b15ec99bb13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'noticed_glance', ['receiver_user_id', 'sender_twitter_display_name'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'noticed_glance')
    ### end Alembic commands ###
