"""empty message

Revision ID: 287c75076e73
Revises: 3b1503eb75ed
Create Date: 2013-12-29 20:24:14.037211

"""

# revision identifiers, used by Alembic.
revision = '287c75076e73'
down_revision = '3b1503eb75ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twitter_friends_cache',
    sa.Column('twitter_id', sa.Integer(), nullable=False),
    sa.Column('friend_twitter_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('twitter_id', 'friend_twitter_id'),
    sa.UniqueConstraint('twitter_id','friend_twitter_id')
    )
    op.create_table('twitter_friends_cache_last_updated',
    sa.Column('twitter_id', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('twitter_id')
    )
    op.drop_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance')
    op.create_unique_constraint(None, 'unnoticed_glance', ['receiver_user_id', 'hour'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'unnoticed_glance')
    op.create_unique_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance', [u'hour', u'receiver_user_id'])
    op.drop_table('twitter_friends_cache_last_updated')
    op.drop_table('twitter_friends_cache')
    ### end Alembic commands ###
