"""empty message

Revision ID: 386ef1264943
Revises: 17ea64ee8d1e
Create Date: 2013-12-22 14:24:36.465607

"""

# revision identifiers, used by Alembic.
revision = '386ef1264943'
down_revision = '17ea64ee8d1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    ### end Alembic commands ###
