"""empty message

Revision ID: 387b1e58aad5
Revises: 10b67af98eec
Create Date: 2013-12-16 10:34:37.628885

"""

# revision identifiers, used by Alembic.
revision = '387b1e58aad5'
down_revision = '10b67af98eec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
