"""empty message

Revision ID: 3ae2ba409a57
Revises: 447faf71e513
Create Date: 2013-12-28 16:55:03.188395

"""

# revision identifiers, used by Alembic.
revision = '3ae2ba409a57'
down_revision = '447faf71e513'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticed_glance', sa.Column('count', sa.Integer(), nullable=True))
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_column('noticed_glance', 'count')
    ### end Alembic commands ###
