"""empty message

Revision ID: 3b0e482fb071
Revises: 287c75076e73
Create Date: 2013-12-29 20:53:14.808550

"""

# revision identifiers, used by Alembic.
revision = '3b0e482fb071'
down_revision = '287c75076e73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_glance',
    sa.Column('twitter_id', sa.Integer(), nullable=False),
    sa.Column('most_recent', sa.DateTime(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('twitter_id')
    )
    op.create_unique_constraint(None, 'twitter_friends_cache', ['twitter_id', 'friend_twitter_id'])
    op.drop_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance')
    op.create_unique_constraint(None, 'unnoticed_glance', ['receiver_user_id', 'hour'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'unnoticed_glance')
    op.create_unique_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance', [u'hour', u'receiver_user_id'])
    op.drop_constraint(None, 'twitter_friends_cache')
    op.drop_table('sent_glance')
    ### end Alembic commands ###
