"""empty message

Revision ID: 3b1503eb75ed
Revises: 58ac58b7e0a
Create Date: 2013-12-28 20:33:33.565956

"""

# revision identifiers, used by Alembic.
revision = '3b1503eb75ed'
down_revision = '58ac58b7e0a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unnoticed_glance', sa.Column('count', sa.Integer(), nullable=True))
    op.drop_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance')
    op.create_unique_constraint(None, 'unnoticed_glance', ['receiver_user_id', 'hour'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'unnoticed_glance')
    op.create_unique_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance', [u'hour', u'receiver_user_id'])
    op.drop_column('unnoticed_glance', 'count')
    ### end Alembic commands ###
