"""empty message

Revision ID: 3bc1292e9ccb
Revises: 386ef1264943
Create Date: 2013-12-22 17:55:31.889732

"""

# revision identifiers, used by Alembic.
revision = '3bc1292e9ccb'
down_revision = '386ef1264943'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('noticed_glances',
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('sender_twitter_display_name', sa.String(length=255), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('receiver_user_id', 'sender_twitter_display_name'),
    sa.UniqueConstraint('receiver_user_id','sender_twitter_display_name')
    )
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_table('noticed_glances')
    ### end Alembic commands ###
