"""empty message

Revision ID: 3d94a946ae65
Revises: b43773dd186
Create Date: 2013-12-30 09:54:33.334798

"""

# revision identifiers, used by Alembic.
revision = '3d94a946ae65'
down_revision = 'b43773dd186'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'received_unnoticed_glance_receiver_twitter_id_hour_key', 'received_unnoticed_glance')
    op.create_unique_constraint(None, 'received_unnoticed_glance', ['receiver_twitter_id', 'hour'])
    op.drop_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache')
    op.create_unique_constraint(None, 'twitter_friends_cache', ['twitter_id', 'friend_twitter_id'])
    op.drop_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance')
    op.create_unique_constraint(None, 'unnoticed_glance', ['receiver_user_id', 'hour'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'unnoticed_glance')
    op.create_unique_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance', [u'hour', u'receiver_user_id'])
    op.drop_constraint(None, 'twitter_friends_cache')
    op.create_unique_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache', [u'friend_twitter_id', u'twitter_id'])
    op.drop_constraint(None, 'received_unnoticed_glance')
    op.create_unique_constraint(u'received_unnoticed_glance_receiver_twitter_id_hour_key', 'received_unnoticed_glance', [u'hour', u'receiver_twitter_id'])
    ### end Alembic commands ###
