"""empty message

Revision ID: 4415814c180
Revises: 1cb8a1c5d448
Create Date: 2013-12-16 15:37:26.388554

"""

# revision identifiers, used by Alembic.
revision = '4415814c180'
down_revision = '1cb8a1c5d448'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
