"""empty message

Revision ID: 46b9fdff60ad
Revises: 57fcbd78fdba
Create Date: 2013-12-30 15:58:21.627230

"""

# revision identifiers, used by Alembic.
revision = '46b9fdff60ad'
down_revision = '57fcbd78fdba'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'most_recent_received_unnoticed_glance')
    op.add_column('received_unnoticed_glance', sa.Column('when', sa.DateTime(), nullable=True))
    op.drop_column('received_unnoticed_glance', u'count')
    op.drop_column('received_unnoticed_glance', u'ordinal_day')
    op.drop_constraint(u'received_unnoticed_glance_receiver_twitter_id_hour_key', 'received_unnoticed_glance')
    op.create_index('ix_received_unnoticed_glance_when', 'received_unnoticed_glance', ['when'], unique=False)
    op.drop_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache')
    op.create_unique_constraint(None, 'twitter_friends_cache', ['twitter_id', 'friend_twitter_id'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'twitter_friends_cache')
    op.create_unique_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache', [u'friend_twitter_id', u'twitter_id'])
    op.drop_index('ix_received_unnoticed_glance_when', 'received_unnoticed_glance')
    op.create_unique_constraint(u'received_unnoticed_glance_receiver_twitter_id_hour_key', 'received_unnoticed_glance', [u'hour', u'receiver_twitter_id'])
    op.add_column('received_unnoticed_glance', sa.Column(u'ordinal_day', sa.INTEGER(), nullable=True))
    op.add_column('received_unnoticed_glance', sa.Column(u'count', sa.INTEGER(), nullable=True))
    op.drop_column('received_unnoticed_glance', 'when')
    op.create_table(u'most_recent_received_unnoticed_glance',
    sa.Column(u'receiver_twitter_id', sa.INTEGER(), server_default="nextval('most_recent_received_unnoticed_glance_receiver_twitter_id_seq'::regclass)", nullable=False),
    sa.Column(u'when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'receiver_twitter_id', name=u'most_recent_received_unnoticed_glance_pkey')
    )
    ### end Alembic commands ###
