"""empty message

Revision ID: 49a32028bbb9
Revises: 4415814c180
Create Date: 2013-12-21 14:47:04.122755

"""

# revision identifiers, used by Alembic.
revision = '49a32028bbb9'
down_revision = '4415814c180'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'glances')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'glances',
    sa.Column(u'sending_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'receiving_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'last_glance_made_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column(u'last_glance_noticed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiving_user_id'], [u'users.id'], name=u'glances_receiving_user_id_fkey'),
    sa.ForeignKeyConstraint(['sending_user_id'], [u'users.id'], name=u'glances_sending_user_id_fkey'),
    sa.PrimaryKeyConstraint(u'sending_user_id', u'receiving_user_id', name=u'glances_pkey')
    )
    ### end Alembic commands ###
