"""empty message

Revision ID: 4f370b17e36f
Revises: 49a32028bbb9
Create Date: 2013-12-21 14:58:02.375192

"""

# revision identifiers, used by Alembic.
revision = '4f370b17e36f'
down_revision = '49a32028bbb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whoyoulookinat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('looking_at_twitter_display_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whoyoulookinat')
    ### end Alembic commands ###
