"""empty message

Revision ID: 504fad35f337
Revises: 3f7ce4f2c419
Create Date: 2013-12-29 21:40:11.041874

"""

# revision identifiers, used by Alembic.
revision = '504fad35f337'
down_revision = '3f7ce4f2c419'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('most_recent_received_unnoticed_glance',
    sa.Column('receiver_twitter_id', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('receiver_twitter_id')
    )
    op.create_table('received_unnoticed_glance',
    sa.Column('receiver_twitter_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('ordinal_day', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('receiver_twitter_id', 'hour'),
    sa.UniqueConstraint('receiver_twitter_id','hour')
    )
    op.create_unique_constraint(None, 'received_noticed_glance', ['receiver_twitter_id', 'sender_twitter_id'])
    op.drop_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache')
    op.create_unique_constraint(None, 'twitter_friends_cache', ['twitter_id', 'friend_twitter_id'])
    op.drop_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance')
    op.create_unique_constraint(None, 'unnoticed_glance', ['receiver_user_id', 'hour'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'unnoticed_glance')
    op.create_unique_constraint(u'unnoticed_glance_receiver_user_id_hour_key', 'unnoticed_glance', [u'hour', u'receiver_user_id'])
    op.drop_constraint(None, 'twitter_friends_cache')
    op.create_unique_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache', [u'friend_twitter_id', u'twitter_id'])
    op.drop_constraint(None, 'received_noticed_glance')
    op.drop_table('received_unnoticed_glance')
    op.drop_table('most_recent_received_unnoticed_glance')
    ### end Alembic commands ###
