"""empty message

Revision ID: 5193bec59385
Revises: 3ae2ba409a57
Create Date: 2013-12-28 19:38:56.144380

"""

# revision identifiers, used by Alembic.
revision = '5193bec59385'
down_revision = '3ae2ba409a57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unnoticed_glance',
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('days_since_epoch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('receiver_user_id', 'hour'),
    sa.UniqueConstraint('receiver_user_id','hour')
    )
    op.create_table('last_unnoticed_glance',
    sa.Column('receiver_user_id', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('receiver_user_id')
    )
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_table('last_unnoticed_glance')
    op.drop_table('unnoticed_glance')
    ### end Alembic commands ###
