"""empty message

Revision ID: 57fcbd78fdba
Revises: 13575ee3a7b1
Create Date: 2013-12-30 15:16:11.897021

"""

# revision identifiers, used by Alembic.
revision = '57fcbd78fdba'
down_revision = '13575ee3a7b1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'unnoticed_glance')
    op.drop_table(u'noticed_glance')
    op.drop_table(u'last_unnoticed_glance')
    op.drop_table(u'last_sent_glance')
    op.drop_constraint(u'received_unnoticed_glance_receiver_twitter_id_hour_key', 'received_unnoticed_glance')
    op.create_unique_constraint(None, 'received_unnoticed_glance', ['receiver_twitter_id', 'hour'])
    op.drop_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache')
    op.create_unique_constraint(None, 'twitter_friends_cache', ['twitter_id', 'friend_twitter_id'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'twitter_friends_cache')
    op.create_unique_constraint(u'twitter_friends_cache_twitter_id_friend_twitter_id_key', 'twitter_friends_cache', [u'friend_twitter_id', u'twitter_id'])
    op.drop_constraint(None, 'received_unnoticed_glance')
    op.create_unique_constraint(u'received_unnoticed_glance_receiver_twitter_id_hour_key', 'received_unnoticed_glance', [u'hour', u'receiver_twitter_id'])
    op.create_table(u'last_sent_glance',
    sa.Column(u'sender_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column(u'count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sender_user_id'], [u'users.id'], name=u'last_sent_glance_sender_user_id_fkey'),
    sa.PrimaryKeyConstraint(u'sender_user_id', name=u'last_sent_glance_pkey')
    )
    op.create_table(u'last_unnoticed_glance',
    sa.Column(u'receiver_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_user_id'], [u'users.id'], name=u'last_unnoticed_glance_receiver_user_id_fkey'),
    sa.PrimaryKeyConstraint(u'receiver_user_id', name=u'last_unnoticed_glance_pkey')
    )
    op.create_table(u'noticed_glance',
    sa.Column(u'receiver_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'sender_twitter_display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column(u'when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column(u'count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_user_id'], [u'users.id'], name=u'noticed_glance_receiver_user_id_fkey'),
    sa.PrimaryKeyConstraint(u'receiver_user_id', u'sender_twitter_display_name', name=u'noticed_glance_pkey')
    )
    op.create_table(u'unnoticed_glance',
    sa.Column(u'receiver_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column(u'hour', sa.INTEGER(), server_default="nextval('unnoticed_glance_hour_seq'::regclass)", nullable=False),
    sa.Column(u'ordinal_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiver_user_id'], [u'users.id'], name=u'unnoticed_glance_receiver_user_id_fkey'),
    sa.PrimaryKeyConstraint(u'receiver_user_id', u'hour', name=u'unnoticed_glance_pkey')
    )
    ### end Alembic commands ###
