"""empty message

Revision ID: 58ac58b7e0a
Revises: 5193bec59385
Create Date: 2013-12-28 20:32:56.269727

"""

# revision identifiers, used by Alembic.
revision = '58ac58b7e0a'
down_revision = '5193bec59385'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unnoticed_glance', sa.Column('ordinal_day', sa.Integer(), nullable=True))
    op.drop_column('unnoticed_glance', u'days_since_epoch')
    op.create_unique_constraint(None, 'unnoticed_glance', ['receiver_user_id', 'hour'])
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_constraint(None, 'unnoticed_glance')
    op.add_column('unnoticed_glance', sa.Column(u'days_since_epoch', sa.INTEGER(), nullable=True))
    op.drop_column('unnoticed_glance', 'ordinal_day')
    ### end Alembic commands ###
