"""empty message

Revision ID: 5adef2feec53
Revises: 26838fd9f692
Create Date: 2013-12-26 09:31:31.692115

"""

# revision identifiers, used by Alembic.
revision = '5adef2feec53'
down_revision = '26838fd9f692'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_sent_glance',
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('sender_user_id')
    )
    op.drop_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat')
    op.create_unique_constraint(None, 'whoyoulookinat', ['user_id', 'looking_at_twitter_display_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whoyoulookinat')
    op.create_unique_constraint(u'whoyoulookinat_user_id_looking_at_twitter_display_name_key', 'whoyoulookinat', [u'looking_at_twitter_display_name', u'user_id'])
    op.drop_table('last_sent_glance')
    ### end Alembic commands ###
