"""empty message

Revision ID: 709df12b367
Revises: None
Create Date: 2013-12-12 10:02:25.015194

"""

# revision identifiers, used by Alembic.
revision = '709df12b367'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_nickname', 'user')
    op.drop_index('ix_user_email', 'user')
    op.drop_table('user')
    ### end Alembic commands ###
