"""empty message

Revision ID: 7a7b8c3fd19
Revises: 4f370b17e36f
Create Date: 2013-12-22 14:13:25.124490

"""

# revision identifiers, used by Alembic.
revision = '7a7b8c3fd19'
down_revision = '4f370b17e36f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whoyoulookinat', u'id')
    op.alter_column('whoyoulookinat', 'looking_at_twitter_display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('whoyoulookinat', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whoyoulookinat', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('whoyoulookinat', 'looking_at_twitter_display_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('whoyoulookinat', sa.Column(u'id', sa.INTEGER(), server_default="nextval('whoyoulookinat_id_seq'::regclass)", nullable=False))
    ### end Alembic commands ###
